modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="pmmoskillcommand"
version="1.0.0"
displayName="Project MMO Skill Toast"
authors="drog701"
description='''Displays a toast when PMMO skills level up.'''

[[dependencies.pmmoskillcommand]]
modId="neoforge"
mandatory=true
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.pmmoskillcommand]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.pmmoskillcommand]]
modId="pmmo"
mandatory=true
versionRange="[2.7.34,)"
ordering="AFTER"
side="BOTH"