modLoader="javafml"
loaderVersion="${2,}"

license="${MIT}"

[[mods]]
modId="pmmoskillcommand"
version="1.0.0"
displayName="Project MMO Skill Toast"
authors="drog701"
description='''Displays a toast when PMMO skills level up.'''

[[dependencies.pmmoskillcommand]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pmmoskillcommand]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.pmmoskillcommand]]
modId="pmmo"
mandatory=true
versionRange="[2.7,)"
ordering="AFTER"
side="BOTH"
